/*
 * Copyright 2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as fs from "fs"
import * as path from "path"
import { parse } from "@babel/parser"
import dependencyTree from "dependency-tree"
import * as t from "@babel/types"

/**
 * Recursively flattens the given dependency tree object
 * and returns all file paths as a string array.
 * @param {Record<string, any>} tree - Tree object generated by the dependency-tree library
 * @returns {string[]} String array containing all file paths
 */
function flattenTree(tree: Record<string, any>): string[] {
    return Object.keys(tree).reduce<string[]>(
        (acc, file) => acc.concat(file, flattenTree(tree[file] || {})),
        [],
    )
}
/**
 * Gets all related files from the project root.
 * @param {string} projectRoot - Project root path
 * @returns {string[]} List of analyzable files
 */
export function getProjectFiles(projectRoot: string): string[] {
    try {
        const tree = dependencyTree({
            filename: path.resolve(projectRoot),
            directory: path.dirname(path.resolve(projectRoot)),
            filter: (p: string) => !p.includes("node_modules"),
        }) as Record<string, any>

        const files = Array.from(new Set(flattenTree(tree)))

        return files.filter((filePath) => {
            return fs.existsSync(filePath) && /\.(ts|js)$/.test(filePath)
        })
    } catch {
        return []
    }
}

/**
 * Reads file content and parses it into AST.
 * @param {string} filePath - File path
 * @returns {{ source: string; ast: t.File } | null} File content and AST
 */
export function parseFile(filePath: string): { source: string; ast: t.File } | null {
    let source: string
    try {
        source = fs.readFileSync(filePath, "utf8").replace(/^#!.*\r?\n/, "")
    } catch {
        return null
    }

    let ast: t.File
    try {
        ast = parse(source, {
            sourceType: "unambiguous",
            plugins: ["jsx", "typescript", "classProperties", "dynamicImport"],
        })
    } catch {
        return null
    }

    return { source, ast }
}

/**
 * Parses multiple files and returns only valid results.
 * @param {string[]} filePaths - Array of file paths
 * @returns {Array<{ filePath: string; source: string; ast: t.File }>} Array of parsed file information
 */
export function parseMultipleFiles(
    filePaths: string[],
): Array<{ filePath: string; source: string; ast: t.File }> {
    const results: Array<{ filePath: string; source: string; ast: t.File }> = []

    for (const filePath of filePaths) {
        const parsed = parseFile(filePath)
        if (parsed) {
            results.push({
                filePath,
                source: parsed.source,
                ast: parsed.ast,
            })
        }
    }

    return results
}

/**
 * Checks if a file exists and is analyzable.
 * @param {string} filePath - File path
 * @returns {boolean} Whether the file is analyzable
 */
export function isAnalyzableFile(filePath: string): boolean {
    return fs.existsSync(filePath) && /\.(ts|js)$/.test(filePath)
}
