packages:
    # Include every package.
    - "scripts/*"
    - "lib/**"
    - "examples/**"
    - "itdoc-doc/**"
    # Exclude test directories.
    - "!**/test/**"
    # Exclude build output directories.
    - "!**/dist/**"
