name: 🐛 Bug Report
description: 버그를 제보해주세요
title: "[Bug]: "
labels: ["bug"]
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              버그를 제보해 주셔서 감사합니다. 자세한 내용을 알려주시면 더 빠른 해결이 가능합니다.

    - type: textarea
      id: expected
      attributes:
          label: Expected Behavior
          description: 원래 어떻게 동작해야 하나요?
          placeholder: 예상된 동작을 설명해주세요
      validations:
          required: true

    - type: textarea
      id: actual
      attributes:
          label: Actual Behavior
          description: 실제로는 어떻게 동작하나요?
          placeholder: 실제 발생한 동작을 설명해주세요
      validations:
          required: true

    - type: textarea
      id: example
      attributes:
          label: Reproduction Steps
          description: 버그를 재현하기 위한 단계를 알려주세요
          placeholder: |
              1. '...' 페이지로 이동
              2. '...' 버튼 클릭
              3. '...' 입력
              4. 에러 발생
      validations:
          required: true

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: 추가적인 정보나 스크린샷이 있다면 첨부해주세요
          placeholder: 스크린샷이나 에러 메시지 등을 첨부해주세요
      validations:
          required: false
