name: 🐛 Bug Report
description: Report a bug you encountered while using the itdoc library
title: "[Bug]: "
labels: ["bug"]
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              Thank you for reporting a bug with the itdoc library.

    - type: textarea
      id: expected
      attributes:
          label: Expected Behavior
          description: What should happen?
          placeholder: Test code should generate documentation as expected
      validations:
          required: true

    - type: textarea
      id: actual
      attributes:
          label: Actual Behavior
          description: What actually happens?
          placeholder: Documentation generation fails or produces unexpected results
      validations:
          required: true

    - type: textarea
      id: reproduce
      attributes:
          label: Steps to Reproduce
          description: Please provide code or steps to reproduce the bug
          placeholder: |
              ```javascript
              import { describeAPI, itDoc } from "itdoc"

              // Code that causes the issue
              ```
      validations:
          required: true

    - type: input
      id: version
      attributes:
          label: itdoc Version
          description: Which version of itdoc are you using?
          placeholder: e.g. 1.0.0
      validations:
          required: true

    - type: textarea
      id: additional
      attributes:
          label: Additional Information
          description:
              Environment details, error messages, screenshots, or any other relevant information
      validations:
          required: false
