name: 📝 Documentation Change
description: Suggest improvements to the itdoc library documentation
title: "[Docs]: "
labels: ["Documentation"]
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              Thank you for suggesting improvements to the itdoc library documentation.

    - type: textarea
      id: current
      attributes:
          label: Current Documentation Issues
          description: Describe what needs to be improved in the current documentation
          placeholder: The current documentation is unclear or missing information about...
      validations:
          required: true

    - type: textarea
      id: suggestion
      attributes:
          label: Suggested Improvements
          description: How would you like the documentation to be improved?
          placeholder: |
              The documentation should be updated/added as follows:

              ```javascript
              // Example code or content
              ```
      validations:
          required: true

    - type: textarea
      id: reason
      attributes:
          label: Reason for Change
          description: Why is this documentation change needed?
          placeholder: This change will help users better understand and utilize itdoc.
      validations:
          required: true

    - type: textarea
      id: additional
      attributes:
          label: Additional Information
          description: Any references, links, or additional context you'd like to provide
      validations:
          required: false
