name: 💡 Feature Request
description: 새로운 기능을 제안해주세요
title: "[Feature]: "
labels: ["Priority: High", "Priority: Medium", "Priority: Low"]
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              새로운 기능을 제안해 주셔서 감사합니다. 자세한 내용을 알려주시면 더 나은 논의가 가능합니다.

    - type: textarea
      id: before
      attributes:
          label: Current State
          description: 현재 상황이나 문제점을 설명해주세요
          placeholder: 현재 이런 불편함이 있습니다...
      validations:
          required: true

    - type: textarea
      id: after
      attributes:
          label: Desired State
          description: 원하시는 기능이나 개선사항을 설명해주세요
          placeholder: 이렇게 개선되었으면 좋겠습니다...
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives Considered
          description: 고려해본 다른 해결방안이 있다면 알려주세요
          placeholder: 다음과 같은 방법들도 고려해보았습니다...
      validations:
          required: false

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: 추가적인 정보나 참고자료가 있다면 첨부해주세요
          placeholder: 관련 스크린샷이나 예시를 첨부해주세요
      validations:
          required: false
