name: 💡 Feature Request
description: Suggest a new feature for the itdoc library
title: "[Feature]: "
labels: []
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              Thank you for suggesting a new feature for the itdoc library.

    - type: textarea
      id: current_problem
      attributes:
          label: Current Situation/Problem
          description: Describe the current situation or problem you're experiencing
          placeholder: |
              When using itdoc, I encounter the following inconvenience:

              ```javascript
              // Current code example
              ```
      validations:
          required: true

    - type: textarea
      id: proposed_solution
      attributes:
          label: Proposed Feature
          description: Describe the feature or improvement you'd like to see
          placeholder: |
              I would like to see the following improvement:

              ```javascript
              // Improved code example
              ```
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives (Optional)
          description: Describe any alternative solutions you've considered
          placeholder: |
              I've also considered the following alternatives:
              1. Using other libraries
              2. Custom implementation
              3. Extending existing functionality
      validations:
          required: false

    - type: textarea
      id: additional
      attributes:
          label: Additional Information
          description: Any additional information about your feature request
          placeholder: |
              - Similar features in other libraries or tools
              - User scenarios or examples
              - Related screenshots or diagrams
      validations:
          required: false
