on:
push:
  branches:
    - main

jobs:
  backport_release_to_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Check if latest commit is a release
        id: check_release
        run: |
          COMMIT_MSG=$(git log origin/main -1 --pretty=%s)
          echo "Latest commit message: $COMMIT_MSG"

          if [[ "$COMMIT_MSG" =~ ^chore\(main\): ]]; then
            echo "release_commit=$(git rev-parse origin/main)" >> $GITHUB_OUTPUT
          else
            echo "No release commit at HEAD"
          fi

      - name: Cherry-pick to develop
        if: steps.check_release.outputs.release_commit != ''
        run: |
          git checkout develop
          git pull origin develop
          git cherry-pick ${{ steps.check_release.outputs.release_commit }}
          git push origin develop
