name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main", "develop"]
    workflow_dispatch:

jobs:
    test:
        name: 테스트, 빌드, 린트
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4

            - name: pnpm 설치
              uses: pnpm/action-setup@v3
              with:
                  version: 10.5.2

            - name: Node.js ${{ matrix.node-version }} 설정
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: 의존성 설치
              run: pnpm install --frozen-lockfile

            - name: 패키지 빌드
              run: pnpm run build

            - name: 린트 검사
              run: |
                  pnpm run prettier:check
                  pnpm run lint

            - name: 테스트 실행
              run: pnpm run test

            - name: 빌드 결과물 저장
              uses: actions/upload-artifact@v4
              with:
                name: build-output
                path: build/
